#!/usr/bin/env python3
"""Generate code from the design sheets (the sheets are the source of truth).

Each sheet row becomes one piece of code built from that row's columns:
  abilities/heroes/items/hunters/spawn_menu/spawn_points/rivals_assets rows -> Enforce Script defs
  movement/multiplayer rows -> constants (Enforce Script and C#)
  items rows -> CfgVehicles classes;  rivals_assets audio rows -> CfgSoundShaders/CfgSoundSets
  inputs rows (kind=mod) -> data/inputs.xml
Outputs go to build/gen/ (mod files) and launcher/RivalsDayZ.Launcher/Generated.cs.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from preflight import load_sheets, NA, ROOT  # noqa: E402

GEN = os.path.join(ROOT, "build", "gen", "RivalsDayZ")
MOD = os.path.join(ROOT, "mod", "RivalsDayZ")
LAUNCHER_GEN = os.path.join(ROOT, "launcher", "RivalsDayZ.Launcher", "Generated.cs")
HEADER = "// GENERATED by tools/gen.py from design/sheets/*.json. Edit the sheets, not this file.\n"

KINDS = ["swing", "crawl", "zip_yank", "web_shot", "drain_melee", "area_drain", "mimicry"]


def es(s):
    """Enforce Script / C# string literal."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def cfgs(s):
    """Config string literal (config.cpp uses "" for quotes, backslashes literal)."""
    return '"' + str(s).replace('"', '""') + '"'


def num(v):
    return "-1" if v == NA else repr(float(v))


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def gen_enforce(s):
    out = [HEADER]
    out.append("class RDZ_Kind\n{\n")
    for i, k in enumerate(KINDS, 1):
        out.append(f"\tstatic const int {k.upper()} = {i};\n")
    out.append("}\n\n")

    out.append("class RDZ_Move\n{\n")
    for r in s["movement"]["rows"]:
        v = r["value"]
        if isinstance(v, str):
            out.append(f"\tstatic const string {r['id']} = {es(v)};\t// {r['doc']}\n")
        else:
            out.append(f"\tstatic const float {r['id']} = {float(v)};\t// {r['unit']}: {r['doc']}\n")
    out.append("}\n\n")

    out.append("class RDZ_MP\n{\n")
    for r in s["multiplayer"]["rows"]:
        if r["status"] != "in_build":
            continue
        v = r["value"]
        if isinstance(v, str):
            out.append(f"\tstatic const string {r['id']} = {es(v)};\n")
        elif isinstance(v, int):
            out.append(f"\tstatic const int {r['id']} = {v};\n")
        else:
            out.append(f"\tstatic const float {r['id']} = {float(v)};\n")
    out.append("}\n\n")

    out.append("class RDZ_Inputs\n{\n")
    for r in s["inputs"]["rows"]:
        if r["kind"] == "mod":
            out.append(f"\tstatic const string {r['id'].upper()} = {es(r['ua_name'])};\n")
    out.append("}\n\n")

    out.append("class RDZ_Data\n{\n")
    out.append("\tstatic ref map<string, ref RDZ_AbilityDef> Abilities;\n")
    out.append("\tstatic ref array<string> AbilityOrder;\n")
    out.append("\tstatic ref map<string, ref RDZ_HeroDef> Heroes;\n")
    out.append("\tstatic ref array<string> HeroOrder;\n")
    out.append("\tstatic ref map<string, ref RDZ_ItemDef> Items;\n")
    out.append("\tstatic ref map<string, ref RDZ_HunterDef> Hunters;\n")
    out.append("\tstatic ref array<ref RDZ_MenuDef> Menu;\n")
    out.append("\tstatic ref map<string, ref RDZ_SpawnPointDef> SpawnPoints;\n")
    out.append("\tstatic ref map<string, ref RDZ_AssetDef> Assets;\n")
    starts = [r["id"] for r in s["spawn_points"]["rows"] if r["role"] == "player_start"]
    out.append(f"\tstatic const string PLAYER_START = {es(starts[0])};\n\n")
    out.append("\tstatic void Init()\n\t{\n\t\tif (Abilities)\n\t\t\treturn;\n")
    out.append("\t\tAbilities = new map<string, ref RDZ_AbilityDef>;\n\t\tAbilityOrder = new array<string>;\n")
    out.append("\t\tHeroes = new map<string, ref RDZ_HeroDef>;\n\t\tHeroOrder = new array<string>;\n")
    out.append("\t\tItems = new map<string, ref RDZ_ItemDef>;\n\t\tHunters = new map<string, ref RDZ_HunterDef>;\n")
    out.append("\t\tMenu = new array<ref RDZ_MenuDef>;\n\t\tSpawnPoints = new map<string, ref RDZ_SpawnPointDef>;\n")
    out.append("\t\tAssets = new map<string, ref RDZ_AssetDef>;\n\n")
    out.append("\t\tRDZ_AbilityDef a;\n\t\tRDZ_HeroDef h;\n\t\tRDZ_ItemDef it;\n\t\tRDZ_HunterDef hu;\n\t\tRDZ_MenuDef m;\n\t\tRDZ_SpawnPointDef sp;\n\t\tRDZ_AssetDef as;\n\n")

    inputs = {r["id"]: r for r in s["inputs"]["rows"]}
    for r in s["abilities"]["rows"]:
        out.append(f"\t\t// abilities.{r['id']}\n")
        out.append("\t\ta = new RDZ_AbilityDef();\n")
        out.append(f"\t\ta.Id = {es(r['id'])}; a.Hero = {es(r['hero'])}; a.RivalsMatch = {es(r['rivals_match'])};\n")
        out.append(f"\t\ta.Kind = RDZ_Kind.{r['kind'].upper()}; a.Input = {es(inputs[r['input']]['ua_name'] if inputs[r['input']]['kind'] == 'mod' else '')}; a.Bit = {r['power_bit']};\n")
        out.append(f"\t\ta.Cooldown = {num(r['cooldown_s'])}; a.Range = {num(r['range_m'])}; a.Damage = {num(r['damage'])};\n")
        out.append(f"\t\ta.Duration = {num(r['duration_s'])}; a.Speed = {num(r['speed_mps'])}; a.HealPct = {num(r['heal_pct'])};\n")
        out.append(f"\t\ta.Stealable = {'true' if r['stealable'] else 'false'}; a.Icon = {es(r['icon'])}; a.Sound = {es(r['sound'])};\n")
        out.append("\t\tAbilities.Insert(a.Id, a);\n\t\tAbilityOrder.Insert(a.Id);\n\n")

    for r in s["heroes"]["rows"]:
        out.append(f"\t\t// heroes.{r['id']}\n")
        out.append("\t\th = new RDZ_HeroDef();\n")
        out.append(f"\t\th.Id = {es(r['id'])}; h.FallbackName = {es(r['fallback_name'])}; h.RivalsMatch = {es(r['rivals_match'])};\n")
        out.append(f"\t\th.Color = {int(r['hud_color_argb'], 16) - (1 << 32) if int(r['hud_color_argb'], 16) >= 1 << 31 else int(r['hud_color_argb'], 16)}; h.PowerItem = {es(r['power_item'])}; h.Hunter = {es(r['hunter'])};\n")
        out.append(f"\t\th.Portrait = {es(r['portrait'])}; h.VoiceSpawn = {es(r['voice_spawn'])};\n")
        out.append("\t\tHeroes.Insert(h.Id, h);\n\t\tHeroOrder.Insert(h.Id);\n\n")

    bits = {r["id"]: r["power_bit"] for r in s["abilities"]["rows"]}
    for r in s["items"]["rows"]:
        mask = 0
        for g in r["grants"]:
            mask |= bits[g]
        out.append(f"\t\t// items.{r['id']}\n")
        out.append("\t\tit = new RDZ_ItemDef();\n")
        out.append(f"\t\tit.Type = {es(r['id'])}; it.Hero = {es(r['hero'])}; it.Slot = {es(r['slot'])}; it.PowerMask = {mask};\n")
        out.append("\t\tItems.Insert(it.Type, it);\n\n")

    for r in s["hunters"]["rows"]:
        uses = 0
        for u in r["uses"]:
            uses |= bits[u]
        out.append(f"\t\t// hunters.{r['id']}\n")
        out.append("\t\thu = new RDZ_HunterDef();\n")
        out.append(f"\t\thu.Id = {es(r['id'])}; hu.Hero = {es(r['hero'])}; hu.Health = {num(r['health'])}; hu.Swinger = {'true' if r['behavior'] == 'swinger' else 'false'};\n")
        out.append(f"\t\thu.UsesMask = {uses}; hu.AggroRange = {num(r['aggro_range_m'])}; hu.AbilityInterval = {num(r['ability_interval_s'])}; hu.Respawn = {num(r['respawn_s'])};\n")
        out.append(f"\t\thu.Taunt = {es(r['taunt'])}; hu.Spawn = {es(r['spawn'])};\n")
        out.append("\t\thu.Classes = new array<string>;\n")
        for c in r["infected_classes"]:
            out.append(f"\t\thu.Classes.Insert({es(c)});\n")
        out.append("\t\tHunters.Insert(hu.Id, hu);\n\n")

    for r in sorted(s["spawn_menu"]["rows"], key=lambda x: x["order"]):
        out.append(f"\t\t// spawn_menu.{r['id']}\n")
        out.append("\t\tm = new RDZ_MenuDef();\n")
        out.append(f"\t\tm.Id = {es(r['id'])}; m.Label = {es(r['label'])}; m.Action = {es(r['action'])}; m.Hero = {es('' if r['hero'] == NA else r['hero'])};\n")
        out.append("\t\tm.ExtraItems = new array<string>;\n")
        for c in r["extra_items"]:
            out.append(f"\t\tm.ExtraItems.Insert({es(c)});\n")
        out.append("\t\tMenu.Insert(m);\n\n")

    for r in s["spawn_points"]["rows"]:
        out.append(f"\t\t// spawn_points.{r['id']}\n")
        out.append("\t\tsp = new RDZ_SpawnPointDef();\n")
        out.append(f"\t\tsp.Id = {es(r['id'])}; sp.NearPlayer = {'true' if r['mode'] == 'near_player_rooftop' else 'false'}; sp.Settlement = {es('' if r['settlement'] == NA else r['settlement'])};\n")
        out.append(f"\t\tsp.FallbackX = {num(r['fallback_x'])}; sp.FallbackZ = {num(r['fallback_z'])}; sp.RadiusMin = {num(r['radius_min_m'])}; sp.RadiusMax = {num(r['radius_max_m'])};\n")
        out.append("\t\tSpawnPoints.Insert(sp.Id, sp);\n\n")

    for r in s["rivals_assets"]["rows"]:
        out.append("\t\tas = new RDZ_AssetDef();\n")
        out.append(f"\t\tas.Id = {es(r['id'])}; as.IsAudio = {'true' if r['kind'] == 'audio' else 'false'}; as.Path = {es(r['output'])};\n")
        if r["kind"] == "audio":
            out.append(f"\t\tas.SoundSet = {es('RDZ_' + r['id'] + '_SoundSet')};\n")
        out.append("\t\tAssets.Insert(as.Id, as);\n")
    out.append("\t}\n}\n")
    return "".join(out)


def gen_inputs_xml(s):
    rows = [r for r in s["inputs"]["rows"] if r["kind"] == "mod"]
    x = ['<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>',
         "<!-- GENERATED by tools/gen.py from design/sheets/inputs.json -->",
         "<modded_inputs>", "\t<inputs>", "\t\t<actions>"]
    for r in rows:
        x.append(f'\t\t\t<input name="{r["ua_name"]}" loc="{r["label"]}" />')
    x += ["\t\t</actions>", "\t</inputs>", "\t<preset>"]
    for r in rows:
        x += [f'\t\t<input name="{r["ua_name"]}">', f'\t\t\t<btn name="{r["default_key"]}" />', "\t\t</input>"]
    x += ["\t</preset>", "</modded_inputs>", ""]
    return "\n".join(x)


def gen_config(s):
    with open(os.path.join(MOD, "config.cpp.in"), encoding="utf-8") as f:
        tpl = f.read()
    addons = sorted({r["required_addon"] for r in s["items"]["rows"]})
    req = ", ".join(cfgs(a) for a in ["DZ_Data", "DZ_Scripts"] + addons)
    veh = []
    for base in sorted({r["base_class"] for r in s["items"]["rows"]}):
        veh.append(f"\tclass {base};")
    for r in s["items"]["rows"]:
        veh += [f"\tclass {r['id']}: {r['base_class']}", "\t{", "\t\tscope = 2;",
                f"\t\tdisplayName = {cfgs(r['display_name'])};",
                f"\t\tdescriptionShort = {cfgs(r['description'])};", "\t};"]
    shaders, sets = [], []
    for r in s["rivals_assets"]["rows"]:
        if r["kind"] != "audio":
            continue
        shaders += [f"\tclass RDZ_{r['id']}_SoundShader", "\t{",
                    f"\t\tsamples[] = {{{{{cfgs(r['output'])}, 1}}}};", "\t\tvolume = 1;", "\t\trange = 80;", "\t};"]
        sets += [f"\tclass RDZ_{r['id']}_SoundSet", "\t{",
                 f"\t\tsoundShaders[] = {{{cfgs('RDZ_' + r['id'] + '_SoundShader')}}};",
                 "\t\tvolumeFactor = 1;", "\t\tfrequencyFactor = 1;", "\t\tspatial = 1;", "\t};"]
    out = tpl.replace("/*@REQUIRED_ADDONS@*/", req)
    out = out.replace("/*@CFGVEHICLES@*/", "\n".join(veh))
    out = out.replace("/*@SOUNDSHADERS@*/", "\n".join(shaders))
    out = out.replace("/*@SOUNDSETS@*/", "\n".join(sets))
    return "// GENERATED by tools/gen.py from mod/RivalsDayZ/config.cpp.in and design/sheets.\n" + out


def gen_csharp(s):
    out = [HEADER, "namespace RivalsDayZ.Launcher;\n\n", "internal static class Sheets\n{\n"]
    for r in s["multiplayer"]["rows"]:
        if r["status"] != "in_build":
            continue
        v = r["value"]
        t = "string" if isinstance(v, str) else ("int" if isinstance(v, int) else "double")
        lit = es(v) if isinstance(v, str) else repr(v)
        out.append(f"    public const {t} {r['id']} = {lit};\n")
    out.append("\n    public static readonly (string Id, string Match)[] HeroTexts =\n    {\n")
    for r in s["heroes"]["rows"]:
        out.append(f"        ({es(r['id'])}, {es(r['rivals_match'])}),\n")
    out.append("    };\n\n    public static readonly (string Id, string Hero, string Match)[] AbilityTexts =\n    {\n")
    for r in s["abilities"]["rows"]:
        out.append(f"        ({es(r['id'])}, {es(r['hero'])}, {es(r['rivals_match'])}),\n")
    out.append("    };\n\n    public static readonly (string Id, bool IsAudio, string[] Keywords, string Output)[] Assets =\n    {\n")
    for r in s["rivals_assets"]["rows"]:
        kws = ", ".join(es(k) for k in r["keywords"])
        out.append(f"        ({es(r['id'])}, {'true' if r['kind'] == 'audio' else 'false'}, new[] {{ {kws} }}, {es(r['output'])}),\n")
    out.append("    };\n}\n")
    return "".join(out)


def main():
    s = load_sheets()
    write(os.path.join(GEN, "scripts", "3_Game", "RivalsDayZ", "RDZ_Generated.c"), gen_enforce(s))
    write(os.path.join(GEN, "data", "inputs.xml"), gen_inputs_xml(s))
    write(os.path.join(GEN, "config.cpp"), gen_config(s))
    write(LAUNCHER_GEN, gen_csharp(s))
    print("generated:", os.path.relpath(GEN, ROOT), "and", os.path.relpath(LAUNCHER_GEN, ROOT))


if __name__ == "__main__":
    main()
